### ISSUE TITLE
可以请教一下您的SpecCompress.npy的计算代码吗

### ISSUE THREAD

**Issue by xwm850565206** [Qinwen-Hu/dparn#2]
可以请教一下你的SpecCompress.npy的计算代码吗，我自己写的代码和您的对不上，想知道是哪里写错了QAQ

**Comment by Qinwen-Hu** [comment]
SpecCompress.npy计算代码
[scm.txt](https://github.com/Qinwen-Hu/dparn/files/9077414/scm.txt)
：

**Comment by xwm850565206** [comment]
感激不尽
