### ISSUE TITLE
Your Pretrained model Expects only 48k sampling rate input?

### ISSUE THREAD

**Issue by yugeshav** [Qinwen-Hu/dparn#7]
@Qinwen-Hu can you please confirm the input sampling rate required for the pretrained model?

**Comment by Qinwen-Hu** [comment]
Yes, the model is a full-band model and expects only 48k sampling rate input. If you want to use the model under other sampling rates, the parameters of the SCM layer should be modified.

**Comment by yugeshav** [comment]
@Qinwen-Hu Thanks for the information
